server:
  port: 8082  # Product Service runs on 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartshop_products?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sql@3500  # <--- UPDATE THIS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Auto-creates tables
    show-sql: true      # Prints SQL to console for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  redis:
    host: localhost
    port: 6379
    cache:
      type: redis      # Tell Spring to use Redis as the caching provider
      # Define a default TTL (Time-To-Live) for cache entries
      redis:
        time-to-live: 60000 # 60 seconds (60000 milliseconds)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/